spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://soap-db:5432/soap-db
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  rabbitmq:
    listener:
      simple:
        auto-startup: true
        default-requeue-rejected: false
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8081


management:
  health:
    rabbit:
      enabled: true