version: "3"

services:
  soap-db:
    container_name: soap-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: soap-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - soap-network

  soap-service:
    container_name: soap-service
    image: soap-service-0.0.1
    depends_on:
      - soap-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - soap-network
      - soa-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    volumes:
      - ./rabbitconfig/data:/var/lib/rabbitmq:rw
      - ./rabbitconfig/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitconfig/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - soa-network

networks:
  soa-network:
    driver: bridge
  soap-network:
    driver: bridge