version: "3"

services:
  soap-db:
    container_name: soap-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: soap-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - soa-network

  soap-service:
    container_name: soap-service
    image: soap-service-0.0.1
    depends_on:
      - soap-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - soa-network

networks:
  soa-network:
    driver: bridge