version: "3"

services:
  rest-db:
    container_name: rest-db
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: rest-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - rest-network

  rest-service:
    container_name: rest-service
    image: rest-service-0.0.1
    depends_on:
      - rest-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - rest-network
      - soapservice_soa-network

networks:
  soapservice_soa-network:
    external: true
  rest-network:
    driver: bridge