version: '3'

services:
  ui:
    container_name: ui
    image: ui-0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8084:80"
    networks:
      - soapservice_soa-network

networks:
  soapservice_soa-network:
    external: true